<?xml version="1.0"?>
<package format="2">
  <name>go2_exploration</name>
  <version>0.1.0</version>
  <description>Online GO2 mapping, frontier and ground coverage exploration.</description>
  <maintainer email="114551361+BAIOLED@users.noreply.github.com">BAIOLED</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>go2_exploration_safety</build_depend>
  <build_export_depend>go2_exploration_safety</build_export_depend>
  <depend>costmap_2d</depend>
  <depend>diagnostic_msgs</depend>
  <depend>eigen</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>pluginlib</depend>
  <depend>roscpp</depend>
  <depend>rospy</depend>
  <depend>sensor_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>std_srvs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>nav_core</depend>
  <depend>teb_local_planner</depend>
  <depend>rviz</depend>
  <exec_depend>actionlib_msgs</exec_depend>
  <depend>std_msgs</depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>tf</exec_depend>
  <exec_depend>map_msgs</exec_depend>
  <test_depend>python3-nose</test_depend>
  <exec_depend>go2_explore_lite</exec_depend>
  <exec_depend>global_planner</exec_depend>
  <exec_depend>move_base</exec_depend>
  <exec_depend>topic_tools</exec_depend>
  <exec_depend>go2_core</exec_depend>
  <exec_depend>go2_control</exec_depend>
  <exec_depend>go2_mapping</exec_depend>
  <exec_depend>go2_bringup</exec_depend>
  <exec_depend>go2_terrain</exec_depend>
  <exec_depend>go2_navigation</exec_depend>
  <depend>livox_ros_driver2</depend>
  <exec_depend>rosgraph</exec_depend>
  <exec_depend>rosbag</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>go2_exploration_safety</exec_depend>

  <export>
    <rviz plugin="${prefix}/rviz_plugins.xml" />
    <nav_core plugin="${prefix}/go2_exploration_plugins.xml" />
    <costmap_2d plugin="${prefix}/go2_exploration_plugins.xml" />
  </export>
</package>
